# This is a basic workflow to help you get started with Actions

name: Cucumber Tests and Report

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    # The type of runner that the job will run on
    runs-on: windows-latest
    strategy:
      matrix:
        test-file:
          - data/cucumber-report_DUE-1170_testokPb_74.json
          - data/cucumber-report_DUE-1520_testiMGL_52.json
          - data/cucumber-report_DUE-1748_testFIqe_33.json
          - data/cucumber-report_DUE-1750_1751_testOhMx_43.json
          - data/cucumber-report_DUE-2522_testUiKW_65.json
          - data/cucumber-report_DUE-2843_testrBPu_37.json

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Check contents
        run: Get-ChildItem data
      - name: Move reports
        run: mv ${{ matrix['test-file'] }} reports/
      - uses: actions/upload-artifact@v2
        with:
          name: jsonfiles
          path: reports/
          retention-days: 1
  generate:
    # The type of runner that the job will run on
    runs-on: windows-latest
    needs: test
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
         java-version: '1.8' # The JDK version to make available on the path.
         java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
         architecture: x64 # (x64 or x86) - defaults to x64
      - uses: actions/download-artifact@v2
        with:
          name: jsonfiles
          path: reports/
      - name: Generate Reports with Maven
        run: mvn clean verify
      - name: Current working directory
        run: Get-Location
      - name: Check contents
        run: Get-ChildItem
      - name: Compress report directory
        run: powershell Compress-Archive -path .\target\cucumber-reports -destinationpath .\target\cucumber-html-reports.zip
      - uses: actions/upload-artifact@v2
        with:
          name: report
          path: target/cucumber-reports.zip
